"""
Production-ready model training pipeline for Heart Disease Prediction System.

This module trains the baseline machine learning model using the
preprocessed datasets generated by automate.py.

Outputs
-------
- baseline_model.pkl
- model_metadata.json
- metrics.json
- classification_report.txt
- confusion_matrix.png
- roc_curve.png
- model_comparison.csv
- training.log

Author: Dimas Rizki
"""

from __future__ import annotations

import json
import logging
import sys
import time
from pathlib import Path
from typing import Any

import joblib
import pandas as pd

from sklearn.ensemble import RandomForestClassifier
from sklearn.base import ClassifierMixin

import matplotlib.pyplot as plt
import numpy as np

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    RocCurveDisplay,
)

from sklearn.metrics import roc_curve

from datetime import datetime

# ==========================================================
# Configuration
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

ARTIFACT_DIR = PROJECT_ROOT / "artifacts"

MODEL_DIR = PROJECT_ROOT / "models"

REPORT_DIR = PROJECT_ROOT / "reports"

LOG_DIR = PROJECT_ROOT / "logs"

LOG_FILE = LOG_DIR / "training.log"

PREPROCESSOR_PATH = ARTIFACT_DIR / "preprocessor.pkl"

BASELINE_MODEL_PATH = MODEL_DIR / "baseline_model.pkl"

MODEL_METADATA_PATH = MODEL_DIR / "model_metadata.json"

METRICS_PATH = ARTIFACT_DIR / "metrics.json"

CLASSIFICATION_REPORT_PATH = (
    ARTIFACT_DIR / "classification_report.txt"
)

CONFUSION_MATRIX_PATH = (
    ARTIFACT_DIR / "confusion_matrix.png"
)

ROC_CURVE_PATH = (
    ARTIFACT_DIR / "roc_curve.png"
)

MODEL_COMPARISON_PATH = (
    REPORT_DIR / "model_comparison.csv"
)

RANDOM_STATE = 42

BASELINE_MODEL_NAME = "RandomForestClassifier"

# ==========================================================
# Logging
# ==========================================================


def setup_logging() -> logging.Logger:
    """
    Configure training logger.
    """

    LOG_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    logger = logging.getLogger("training")

    if logger.handlers:
        return logger

    logger.setLevel(logging.INFO)

    formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s"
    )

    file_handler = logging.FileHandler(LOG_FILE)

    file_handler.setFormatter(formatter)

    stream_handler = logging.StreamHandler(
        sys.stdout
    )

    stream_handler.setFormatter(formatter)

    logger.addHandler(file_handler)

    logger.addHandler(stream_handler)

    return logger


logger = setup_logging()

# ==========================================================
# Directory Utilities
# ==========================================================


def initialize_directories() -> None:
    """
    Create required project directories.
    """

    directories = [
        MODEL_DIR,
        ARTIFACT_DIR,
        REPORT_DIR,
        LOG_DIR,
    ]

    for directory in directories:
        directory.mkdir(
            parents=True,
            exist_ok=True,
        )


# ==========================================================
# JSON Utilities
# ==========================================================


def save_json(
    data: dict[str, Any],
    output_path: Path,
) -> None:
    """
    Save dictionary into JSON file.

    Parameters
    ----------
    data:
        Dictionary to serialize.

    output_path:
        Destination JSON path.
    """

    with output_path.open(
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            data,
            file,
            indent=4,
            ensure_ascii=False,
        )


# ==========================================================
# CSV Utilities
# ==========================================================


def load_dataframe(
    path: Path,
) -> pd.DataFrame:
    """
    Load CSV file as pandas DataFrame.

    Parameters
    ----------
    path:
        CSV file path.

    Returns
    -------
    pd.DataFrame
    """

    if not path.exists():
        raise FileNotFoundError(path)

    dataframe = pd.read_csv(path)

    if dataframe.empty:
        raise ValueError(
            f"{path.name} is empty."
        )

    logger.info(
        "Loaded %s (%s)",
        path.name,
        dataframe.shape,
    )

    return dataframe


# ==========================================================
# Artifact Utilities
# ==========================================================


def load_artifact(
    artifact_path: Path,
) -> Any:
    """
    Load serialized artifact.

    Parameters
    ----------
    artifact_path:
        Artifact path.

    Returns
    -------
    Any
    """

    if not artifact_path.exists():
        raise FileNotFoundError(
            artifact_path
        )

    logger.info(
        "Loading artifact: %s",
        artifact_path.name,
    )

    return joblib.load(
        artifact_path,
    )


def save_artifact(
    artifact: Any,
    output_path: Path,
) -> None:
    """
    Save artifact using joblib.
    """

    joblib.dump(
        artifact,
        output_path,
    )

    logger.info(
        "Saved artifact: %s",
        output_path.name,
    )


# ==========================================================
# Dataset Loader
# ==========================================================


def load_processed_datasets() -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.Series,
    pd.Series,
    pd.Series,
]:
    """
    Load processed datasets generated by automate.py.

    Returns
    -------
    tuple
        X_train,
        X_val,
        X_test,
        y_train,
        y_val,
        y_test
    """

    logger.info(
        "Loading processed datasets..."
    )

    X_train = load_dataframe(
        PROCESSED_DIR / "X_train.csv"
    )

    X_val = load_dataframe(
        PROCESSED_DIR / "X_val.csv"
    )

    X_test = load_dataframe(
        PROCESSED_DIR / "X_test.csv"
    )

    y_train = load_dataframe(
        PROCESSED_DIR / "y_train.csv"
    ).iloc[:, 0]

    y_val = load_dataframe(
        PROCESSED_DIR / "y_val.csv"
    ).iloc[:, 0]

    y_test = load_dataframe(
        PROCESSED_DIR / "y_test.csv"
    ).iloc[:, 0]

    logger.info(
        "Processed datasets loaded successfully."
    )

    return (
        X_train,
        X_val,
        X_test,
        y_train,
        y_val,
        y_test,
    )

def load_preprocessor() -> Any:
    """
    Load preprocessing artifact.

    Returns
    -------
    Any
        Fitted preprocessing pipeline.
    """

    return load_artifact(
        PREPROCESSOR_PATH,
    )


# ==========================================================
# Model Builder
# ==========================================================


def build_baseline_model() -> ClassifierMixin:
    """
    Create baseline Random Forest model.

    Returns
    -------
    ClassifierMixin
    """

    logger.info(
        "Building baseline model..."
    )

    model = RandomForestClassifier(
        random_state=RANDOM_STATE,
    )

    logger.info(
        "Baseline model created."
    )

    return model

# ==========================================================
# Training
# ==========================================================


def train_model(
    model: ClassifierMixin,
    X_train: pd.DataFrame,
    y_train: pd.Series,
) -> tuple[ClassifierMixin, float]:
    """
    Train baseline model.

    Parameters
    ----------
    model:
        Model instance.

    X_train:
        Training features.

    y_train:
        Training target.

    Returns
    -------
    tuple
        Trained model and training time (seconds).
    """

    logger.info(
        "Starting model training..."
    )

    start_time = time.perf_counter()

    model.fit(
        X_train,
        y_train,
    )

    elapsed = (
        time.perf_counter()
        - start_time
    )

    logger.info(
        "Training completed in %.2f seconds.",
        elapsed,
    )

    return model, elapsed


# ==========================================================
# Prediction
# ==========================================================


def predict_model(
    model: ClassifierMixin,
    X: pd.DataFrame,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Predict labels and probabilities.

    Parameters
    ----------
    model:
        Trained model.

    X:
        Feature matrix.

    Returns
    -------
    tuple
        predictions,
        probabilities
    """

    predictions = model.predict(X)

    probabilities = model.predict_proba(X)[
        :,
        1,
    ]

    return (
        predictions,
        probabilities,
    )


# ==========================================================
# Metrics
# ==========================================================


def calculate_metrics(
    y_true: pd.Series,
    y_pred: np.ndarray,
    y_prob: np.ndarray,
) -> dict[str, float]:
    """
    Calculate evaluation metrics.

    Returns
    -------
    dict
    """

    metrics = {
        "accuracy": float(
            accuracy_score(
                y_true,
                y_pred,
            )
        ),
        "precision": float(
            precision_score(
                y_true,
                y_pred,
                zero_division=0,
            )
        ),
        "recall": float(
            recall_score(
                y_true,
                y_pred,
                zero_division=0,
            )
        ),
        "f1_score": float(
            f1_score(
                y_true,
                y_pred,
                zero_division=0,
            )
        ),
        "roc_auc": float(
            roc_auc_score(
                y_true,
                y_prob,
            )
        ),
    }

    logger.info("Evaluation Metrics")

    for key, value in metrics.items():

        logger.info(
            "%s : %.4f",
            key,
            value,
        )

    return metrics

# ==========================================================
# Evaluation
# ==========================================================


def evaluate_model(
    model: ClassifierMixin,
    X: pd.DataFrame,
    y: pd.Series,
) -> tuple[
    dict[str, float],
    np.ndarray,
    np.ndarray,
]:
    """
    Evaluate trained model.

    Parameters
    ----------
    model:
        Trained model.

    X:
        Evaluation features.

    y:
        Evaluation target.

    Returns
    -------
    tuple
        metrics,
        predictions,
        probabilities
    """

    logger.info(
        "Evaluating model..."
    )

    predictions, probabilities = predict_model(
        model,
        X,
    )

    metrics = calculate_metrics(
        y,
        predictions,
        probabilities,
    )

    logger.info(
        "Model evaluation completed."
    )

    return (
        metrics,
        predictions,
        probabilities,
    )


# ==========================================================
# Report Generation
# ==========================================================


def save_classification_report(
    y_true: pd.Series,
    y_pred: np.ndarray,
) -> None:
    """
    Save classification report.

    Parameters
    ----------
    y_true:
        Ground truth labels.

    y_pred:
        Predicted labels.
    """

    logger.info(
        "Generating classification report..."
    )

    report = classification_report(
        y_true,
        y_pred,
        digits=4,
        zero_division=0,
    )

    with CLASSIFICATION_REPORT_PATH.open(
        "w",
        encoding="utf-8",
    ) as file:

        file.write(report)

    logger.info(
        "Saved %s",
        CLASSIFICATION_REPORT_PATH.name,
    )


def save_metrics(
    metrics: dict[str, float],
) -> None:
    """
    Save evaluation metrics.

    Parameters
    ----------
    metrics:
        Evaluation metrics.
    """

    save_json(
        metrics,
        METRICS_PATH,
    )

    logger.info(
        "Saved %s",
        METRICS_PATH.name,
    )

# ==========================================================
# Visualization
# ==========================================================


def close_plot(
    figure: plt.Figure,
) -> None:

    plt.close(figure)


def save_confusion_matrix(
    y_true: pd.Series,
    y_pred: np.ndarray,
) -> None:
    """
    Generate and save confusion matrix figure.

    Parameters
    ----------
    y_true:
        Ground truth labels.

    y_pred:
        Predicted labels.
    """

    logger.info(
        "Generating confusion matrix..."
    )

    cm = confusion_matrix(
        y_true,
        y_pred,
    )

    fig, ax = plt.subplots(
        figsize=(6, 6)
    )

    ConfusionMatrixDisplay(
        confusion_matrix=cm,
    ).plot(
        ax=ax,
        colorbar=False,
    )

    ax.set_title(
        "Confusion Matrix"
    )

    fig.savefig(
        CONFUSION_MATRIX_PATH,
        dpi=300,
        bbox_inches="tight",
    )

    close_plot(fig)

    logger.info(
        "Saved %s",
        CONFUSION_MATRIX_PATH.name,
    )


def save_roc_curve(
    y_true: pd.Series,
    probabilities: np.ndarray,
) -> None:
    """
    Generate ROC Curve figure.

    Parameters
    ----------
    y_true:
        Ground truth labels.

    probabilities:
        Positive class probabilities.
    """

    logger.info(
        "Generating ROC curve..."
    )

    fpr, tpr, _ = roc_curve(
        y_true,
        probabilities,
    )

    roc_auc = roc_auc_score(
        y_true,
        probabilities,
    )

    fig, ax = plt.subplots(
        figsize=(7, 6)
    )

    display = RocCurveDisplay(
        fpr=fpr,
        tpr=tpr,
        roc_auc=roc_auc,
    )

    display.plot(ax=ax)

    ax.set_title(
        f"ROC Curve ({BASELINE_MODEL_NAME})"
    )

    fig.savefig(
        ROC_CURVE_PATH,
        dpi=300,
        bbox_inches="tight",
    )

    close_plot(fig)

    logger.info(
        "Saved %s",
        ROC_CURVE_PATH.name,
    )

# ==========================================================
# Model Persistence
# ==========================================================


def save_model(
    model: ClassifierMixin,
) -> None:
    """
    Save trained model.

    Parameters
    ----------
    model:
        Trained baseline model.
    """

    save_artifact(
        model,
        BASELINE_MODEL_PATH,
    )

    logger.info(
        "Saved %s",
        BASELINE_MODEL_PATH.name,
    )


def save_model_metadata(
    metrics: dict[str, float],
    training_time: float,
    X_train: pd.DataFrame,
    X_val: pd.DataFrame,
    X_test: pd.DataFrame,
) -> None:
    """
    Save model metadata.
    """

    metadata = {

        "model_name": BASELINE_MODEL_NAME,

        "version": "baseline",

        "random_state": RANDOM_STATE,

        "training_timestamp": (
            datetime.now()
            .isoformat()
        ),

        "training_samples": int(
            len(X_train)
        ),

        "validation_samples": int(
            len(X_val)
        ),

        "test_samples": int(
            len(X_test)
        ),

        "training_features": int(
            X_train.shape[1]
        ),

        "training_time_seconds": round(
            training_time,
            4,
        ),

        **metrics,
        "train_shape": list(X_train.shape),

        "validation_shape": list(X_val.shape),

        "test_shape": list(X_test.shape),

        "feature_names": X_train.columns.tolist(),
    }

    save_json(
        metadata,
        MODEL_METADATA_PATH,
    )

    logger.info(
        "Saved %s",
        MODEL_METADATA_PATH.name,
    )

# ==========================================================
# Model Comparison
# ==========================================================


def save_model_comparison(
    metrics: dict[str, float],
    training_time: float,
) -> None:
    """
    Save comparison report.

    Although only one model exists,
    the format is intentionally kept
    extensible for future tuning.
    """

    comparison = pd.DataFrame(
        [
            {
                "model": BASELINE_MODEL_NAME,

                "version":"baseline",

                "accuracy":
                    metrics["accuracy"],

                "precision":
                    metrics["precision"],

                "recall":
                    metrics["recall"],

                "f1_score":
                    metrics["f1_score"],

                "roc_auc":
                    metrics["roc_auc"],

                "training_time":
                    training_time,
            }
        ]
    )

    comparison.to_csv(
        MODEL_COMPARISON_PATH,
        index=False,
    )

    logger.info(
        "Saved %s",
        MODEL_COMPARISON_PATH.name,
    )

# ==========================================================
# Training Pipeline
# ==========================================================


def run_pipeline() -> None:
    """
    Execute complete training pipeline.
    """

    start = time.perf_counter()

    logger.info("=" * 60)
    logger.info("STARTING MODEL TRAINING")
    logger.info("=" * 60)

    initialize_directories()

    _ = load_preprocessor()

    logger.info(
        "Loaded preprocessing artifact successfully."
    )

    (
        X_train,
        X_val,
        X_test,
        y_train,
        y_val,
        y_test,
    ) = load_processed_datasets()

    logger.info(
        "Train shape : %s",
        X_train.shape,
    )

    logger.info(
        "Validation shape : %s",
        X_val.shape,
    )

    logger.info(
        "Test shape : %s",
        X_test.shape,
    )

    model = build_baseline_model()

    model, training_time = train_model(
        model,
        X_train,
        y_train,
    )

    metrics, predictions, probabilities = (
        evaluate_model(
            model,
            X_val,
            y_val,
        )
    )

    save_metrics(metrics)

    save_classification_report(
        y_val,
        predictions,
    )

    save_confusion_matrix(
        y_val,
        predictions,
    )

    save_roc_curve(
        y_val,
        probabilities,
    )

    save_model(
        model,
    )

    save_model_metadata(
        metrics,
        training_time,
        X_train,
        X_val,
        X_test,
    )

    save_model_comparison(
        metrics,
        training_time,
    )

    elapsed = (
        time.perf_counter()
        - start
    )

    logger.info(
        "Pipeline finished in %.2f seconds.",
        elapsed,
    )

    logger.info("=" * 60)
    logger.info("TRAINING FINISHED SUCCESSFULLY")
    logger.info("=" * 60)

# ==========================================================
# CLI
# ==========================================================


def main() -> None:
    """
    Application entry point.
    """

    try:

        run_pipeline()

    except KeyboardInterrupt:

        logger.warning(
            "Training interrupted by user."
        )

    except Exception:

        logger.exception(
            "Unexpected error occurred."
        )

        raise


if __name__ == "__main__":

    main()
